### PR TITLE
Update runtime to Gnome 3.30

### PR DESCRIPTION
**Pull request by FakeShemp**
- Update components to latest versions
- Remove six and setuptools as they are in runtime now
- Rename "shared-modules" folder to avoid clashes with flathub submodule with same name
- Run formatter on documents
- Limit filesystem to xdg-docs & xdg-pics

### CODE REVIEW

**Comment by jflesch** [comment]
Thanks. I'll have a look at your changes this week-end.

I'll apply them and test them first on the [Gitlab](https://gitlab.gnome.org/World/OpenPaperwork/paperwork/tree/master/flatpak)/[Buildbot](https://origami.openpaper.work/#/builders/7) Flatpak build/[repository](https://gitlab.gnome.org/World/OpenPaperwork/paperwork/blob/master/flatpak/README.markdown#quick-start) before applying them on the Flathub version here.

**Comment by jflesch** [comment]
Quick update so you know I haven't forgotten about this PR:

I didn't have time last week-end.
This week, I realized my own :[Buildbot](https://origami.openpaper.work/#/builders/7) was using obsolete Flatpak files (those on [Github](https://github.com/openpaperwork/paperwork) instead of [Gnome's Gitlab](https://gitlab.gnome.org/World/OpenpaperWork/Paperwork) ...). So I had to fix that and the resulting failing build first.

I changed job and moved not too long ago, so I'm still short on free time. I'll try to test and merge this PR this week-end but I can't promise anything.

**Comment by jflesch** [comment]
https://github.com/flathub/work.openpaper.Paperwork/pull/3/commits/436d9e0376261e1bd0f257e4f6d26b989162fcb3

This change will be a problem: The default work directory of Paperwork is `~/papers`. The work directory format is specific to Paperwork and I do not think it would make sense in `~/Documents`. It wold also be pretty hard to explain to users that their work directory, when using Flatpak, must be in ~/Documents. It would also break current installations.

**Comment by jflesch** [comment]
I've applied changes similar to yours on the [development version](https://gitlab.gnome.org/World/OpenPaperwork/paperwork/blob/develop/flatpak/develop.json).

There is unfortunately another issue: The upgrade of Tesseract to the version 4.0 has introduced a change in the way the environment variable `TESSDATA_PREFIX` is handled.
If you want to use Tesseract 4.x with Paperwork 1.2.4, you must include [an extra patch](https://gitlab.gnome.org/World/OpenPaperwork/paperwork/commit/8e90c64e8e2f2b9428e4eab65e72f1d21fcb6da5).

**Comment by nedrichards** [comment]
@jflesch fwiw we have better test build support here now at https://flathub.org/builds (log in with github) and you can kick off builds in PRs using

bot, build

if required.

**Comment by jflesch** [comment]
This merge request has been inactive for more than 1 year --> I'm closing it.

**Pull request closed without merging**
